### ISSUE TITLE
Can high-definition models like 384x384 and 512x512 be trained?

### ISSUE THREAD

**Issue by haojing8312** [bytedance/LatentSync#12]

**Comment by chunyu-li** [comment]
OK I can give you an example of how to train our model on 512x512 resolution, here is steps:
1. Choose a VAE supporting 512x512 size, such as https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/tree/main/vae
2. Use data processing pipeline to reprocess data to save them as 512x512 videos, note that you need to prepare a lot of high-resolution videos.
3. Train a SyncNet on 512x512 using our code, note that you need to change the arch of SyncNet (config file) to make it output a 1xD embedding.
4. Train U-Net under the supervision of your trained SyncNet

**Comment by elitxl** [comment]
Can you explain stage 3? "change the arch of SyncNet (config file) to make it output a 1xD embedding"
How is different compared to current 256x256 version?

**Comment by chunyu-li** [comment]
The config file of SyncNet defines the ResNet model arch. 

```yaml
audio_encoder: # input (1, 80, 52)
  in_channels: 1
  block_out_channels: [32, 64, 128, 256, 512, 1024, 2048]
  downsample_factors: [[2, 1], 2, 2, 1, 2, 2, [2, 3]]
  attn_blocks: [0, 0, 0, 0, 0, 0, 0]
  dropout: 0.0
```

For example, the above model arch accept a 1 x 80 x 52 image (melspectrogram) and output a 2048 x 1 x 1 feature map. If the input size changes, you need to redefine the `downsample_factors` to make the output looks like D x 1 x 1, so that it can be used to compute cosine similarity. Also reset the `block_out_channels`, in most cases, deeper networks require larger numbers of channels to store more features. I recommend reading the paper [EfficientNet](https://arxiv.org/abs/1905.11946), which discusses how to set the depth and width of CNN networks.
